version: '3.8'

services:
  db:
    image: postgres:17
    container_name: jobportal-db
    environment:
      POSTGRES_DB: jobportal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Shub#@ngi@1412
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: jobportal-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jobportal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Shub#@ngi@1412

volumes:
  postgres_data: