spring.application.name=jobportal
server.servlet.context-path=/api
spring.datasource.url = jdbc:postgresql://localhost:5432/jobportal
spring.datasource.username = postgres
spring.datasource.password = postgres

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

spring.jackson.time-zone=Asia/Kolkata
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

logging.level.org.hibernate.SQL=DEBUG
